version: '3'

services:
  web:
    container_name: moat_builder_music
    tty: true
    stdin_open: true 
    build: .
    image: cperbony/moat_builder.server.debian
    restart: unless-stopped
    command: sh ./scripts/entrypoint.sh
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=moat_builder_music
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - CORE_BASE=$CORE_ENV
      - SPROCKETS_CACHE=/cache
    volumes:
      - .:/app
      - cache:/cache
    ports:
      - 3000:3000
      - 3001:3001
    links:
      - db
  db:
    image: postgres:12-alpine
    container_name: dbmoat_builder_music
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moat_builder_music
      - TZ=America/Sao_Paulo
    volumes:
      - moat_builder_music:/var/lib/postgresql/data
volumes:
  moat_builder_music:
  dbmoat_builder_music:
  cache:
  